### ISSUE TITLE
Interested in a PR to SAM-ify the project?

### ISSUE THREAD

**Issue by jangroth** [binxio/cfn-saml-provider#2]
I've been converting `cfn-saml-provider` to an AWS SAM application so that it fits better into my infrastructure.

Happy to submit a PR if there is an interest?

**Comment by mvanholsteijn** [comment]
Hi @jangroth, 

I have a dozen or so providers to maintain and I they all use the same build process. Perhaps you could show me what you did, and I make a better judgment call on moving them all to SAM.

Cheers,
Mark

**Comment by jangroth** [comment]
Hey @mvanholsteijn,

We implemented only minor changes in CFN, converting it to a SAM template, obviously, but everything else worked pretty much out of the box. 

The biggest change was integrating the project into our deployment process. Still makefiles, but using SAM. Something like this:

```
.aws-sam/build/template.yaml: $(INPUT_TEMPLATE_FILE) $(SOURCE_FILES)  ## sam-build target and dependencies
	SAM_CLI_TELEMETRY=0 \
	sam build \
		--template-file $(INPUT_TEMPLATE_FILE) \
		--manifest $(MANIFEST_FILE) \
		--debug

$(OUTPUT_TEMPLATE_FILE): $(var_file) .aws-sam/build/template.yaml  ## create and upload the SAM application-bundle 
	SAM_CLI_TELEMETRY=0 \
	sam package \
		--s3-bucket "$(PACKAGE_BUCKET)" \
		--output-template-file "$(OUTPUT_TEMPLATE_FILE)" \
		--debug

package:: $(OUTPUT_TEMPLATE_FILE)  ## standard target to be invoked: package the application
	@echo "*** finished packaging ${INPUT_TEMPLATE_FILE}"
```

If you want to see this in a wider context, I have a private repo that uses a very similar SAM layout/build process:
https://github.com/jangroth/writing-aws-lambdas-in-python

To be honest - if you are already maintaining multiple repos that all have a similar structure - converting a single repo to SAM might not provide much value.

However, using your project saved us days of development work, and I'm more than happy to create a PR. Just let me know what you think.

**Comment by mvanholsteijn** [comment]
I cannot see how sam is going to help me. Especially as I want to create a specific version of the zip file and sam just generates random zip file name with template refefring to it. Or am I missing something?

**Comment by jangroth** [comment]
From my experience the biggest advantage of SAM is the clean building & packaging path for Lambdas. A big step up from lazily inlined Lambdas, and a considerable amount of effort you save over scripting the process yourself.

I didn't come across a use-case where I needed control over the name of the artifact in S3, I rather look at it as a vehicle to get the code into the cloud (and use the git repo for versioning).

I agree, there's not much win for this project. But I still wanted to reach out to give you the feedback that your code is actually being used :)

Thanks for making it open-source!

**Comment by mvanholsteijn** [comment]
Oke we will leave it as it is then. Thank you for providing the feedback and offering assistance in improving things.
